name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *" 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      with:
        API_KEY: ${{ secrets.API_KEY }}

    - name: Run
      run: go run main.go
      with:
        API_KEY: ${{ secrets.API_KEY }}
    
    - name: Get commit message for today
      id: msg
      run: echo "::set-output name=msg::Daily build for $(date +'%Y-%m-%d')"

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: output
        branch: main
        repository-name: aarusharora/aarusharora
        token: ${{ secrets.ACCESS_TOKEN }}
        git-config-name: ${{ secrets.commiter_name }}
        git-config-email: ${{ secrets.commiter_email }}
        commit-message: "Daily build for ${{ steps.msg.outputs.msg }}"
